INSERT INTO TBL_SYSTEM_USER (LOGIN, PASSWORD) VALUES ('palermo', 'palermo');

INSERT INTO TBL_LANGUAGE (NAME) VALUES ('English');
INSERT INTO TBL_LANGUAGE (NAME) VALUES ('German');
INSERT INTO TBL_LANGUAGE (NAME) VALUES ('Italian');
INSERT INTO TBL_LANGUAGE (NAME) VALUES ('Portuguese');

INSERT INTO TBL_PARAMETER (NAME, VALUE) VALUES ('SEPARATOR', '\\\\s|“|”|\\\\.|,|’|–|''|‘|:|\\\\(|\\\\)');