INSERT INTO SYSTEM_USER (LOGIN, PASSWORD) VALUES ('palermo', 'palermo');

INSERT INTO LANGUAGE (NAME) VALUES ('English');
INSERT INTO LANGUAGE (NAME) VALUES ('German');
INSERT INTO LANGUAGE (NAME) VALUES ('Italian');
INSERT INTO LANGUAGE (NAME) VALUES ('Portuguese');